name: Deployment pipeline

on:
  push:
    branches:
      - main

env: 
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
  SECRET: ${{ secrets.SECRET }}
  PORT: ${{ secrets.PORT }} 

jobs:
  deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install 
        run: npm install && cd client && npm install
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
      - name: test
        env:
          NODE_ENV: 'test'
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        env:
          NODE_ENV: 'test'
        with:
          command: npm run test:e2e
          start: npm run start:test 
          wait-on: http://localhost:5000
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        env: 
          NODE_ENV: 'production'
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'bloglistredux' #Must be unique in Heroku
          heroku_email: 'ccfu@kth.se'