name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env: 
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
  SECRET: ${{ secrets.SECRET }}
  PORT: ${{ secrets.PORT }} 

jobs:
  deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: install backend
        run: npm install 
      - name: install client
        run: cd client && npm install
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
      - name: test
        env:
          NODE_ENV: 'test'
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        env:
          NODE_ENV: 'test'
        with:
          command: npm run test:e2e
          start: npm run start:test 
          wait-on: http://localhost:5000
      - name: deploy to heroku
        if: ${{ github.event_name == 'push' }}
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'bloglistredux' #Must be unique in Heroku
          heroku_email: 'ccfu@kth.se'
          healthcheck: 'https://bloglistredux.herokuapp.com/health'
          checkstring: 'ok'
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: 'patch'
          WITH_V: true
          RELEASE_BRANCHES: 'main'